[2023-12-30T02:13:28.987+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_data.load_data_task manual__2023-12-30T02:13:21.208040+00:00 [queued]>
[2023-12-30T02:13:29.004+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_data.load_data_task manual__2023-12-30T02:13:21.208040+00:00 [queued]>
[2023-12-30T02:13:29.004+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2023-12-30T02:13:29.030+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): load_data_task> on 2023-12-30 02:13:21.208040+00:00
[2023-12-30T02:13:29.040+0000] {standard_task_runner.py:60} INFO - Started process 70 to run task
[2023-12-30T02:13:29.051+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'load_data', 'load_data_task', 'manual__2023-12-30T02:13:21.208040+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/load_data.py', '--cfg-path', '/tmp/tmprj7__spt']
[2023-12-30T02:13:29.070+0000] {standard_task_runner.py:88} INFO - Job 3: Subtask load_data_task
[2023-12-30T02:13:29.177+0000] {task_command.py:423} INFO - Running <TaskInstance: load_data.load_data_task manual__2023-12-30T02:13:21.208040+00:00 [running]> on host 5aab4ee80123
[2023-12-30T02:13:29.333+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='load_data' AIRFLOW_CTX_TASK_ID='load_data_task' AIRFLOW_CTX_EXECUTION_DATE='2023-12-30T02:13:21.208040+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-30T02:13:21.208040+00:00'
[2023-12-30T02:13:29.334+0000] {logging_mixin.py:188} INFO - this is a test
[2023-12-30T02:13:29.335+0000] {logging_mixin.py:188} INFO - ***
[2023-12-30T02:13:29.335+0000] {logging_mixin.py:188} INFO - /opt/***
[2023-12-30T02:13:29.339+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/load_data.py", line 30, in load_data
    df = pd.read_csv(path + "products.csv")
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1661, in _make_engine
    self.handles = get_handle(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/common.py", line 859, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data/instacart-market-basket-analysis/products.csv'
[2023-12-30T02:13:29.362+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=load_data, task_id=load_data_task, execution_date=20231230T021321, start_date=20231230T021328, end_date=20231230T021329
[2023-12-30T02:13:29.383+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 3 for task load_data_task ([Errno 2] No such file or directory: '/opt/airflow/data/instacart-market-basket-analysis/products.csv'; 70)
[2023-12-30T02:13:29.412+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2023-12-30T02:13:29.456+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
