[2023-12-30T02:04:16.116+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_data.load_data_task manual__2023-12-30T02:04:09.917247+00:00 [queued]>
[2023-12-30T02:04:16.130+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_data.load_data_task manual__2023-12-30T02:04:09.917247+00:00 [queued]>
[2023-12-30T02:04:16.130+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2023-12-30T02:04:16.156+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): load_data_task> on 2023-12-30 02:04:09.917247+00:00
[2023-12-30T02:04:16.165+0000] {standard_task_runner.py:60} INFO - Started process 459 to run task
[2023-12-30T02:04:16.170+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'load_data', 'load_data_task', 'manual__2023-12-30T02:04:09.917247+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/load_data.py', '--cfg-path', '/tmp/tmptjyd5ynj']
[2023-12-30T02:04:16.176+0000] {standard_task_runner.py:88} INFO - Job 8: Subtask load_data_task
[2023-12-30T02:04:16.283+0000] {task_command.py:423} INFO - Running <TaskInstance: load_data.load_data_task manual__2023-12-30T02:04:09.917247+00:00 [running]> on host 3196336a5b49
[2023-12-30T02:04:16.687+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='load_data' AIRFLOW_CTX_TASK_ID='load_data_task' AIRFLOW_CTX_EXECUTION_DATE='2023-12-30T02:04:09.917247+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-30T02:04:09.917247+00:00'
[2023-12-30T02:04:16.689+0000] {logging_mixin.py:188} INFO - this is a test
[2023-12-30T02:04:16.690+0000] {logging_mixin.py:188} INFO - ***
[2023-12-30T02:04:16.690+0000] {logging_mixin.py:188} INFO - /opt/***
[2023-12-30T02:04:16.693+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/load_data.py", line 30, in load_data
    df = pd.read_csv(path + "products.csv")
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1661, in _make_engine
    self.handles = get_handle(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/common.py", line 859, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/home/kgeesawor/git/data/instacart-market-basket-analysis/products.csv'
[2023-12-30T02:04:16.719+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=load_data, task_id=load_data_task, execution_date=20231230T020409, start_date=20231230T020416, end_date=20231230T020416
[2023-12-30T02:04:16.740+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 8 for task load_data_task ([Errno 2] No such file or directory: '/home/kgeesawor/git/data/instacart-market-basket-analysis/products.csv'; 459)
[2023-12-30T02:04:16.761+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2023-12-30T02:04:16.803+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
